server.port: 8081

spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

s3:
  endpointUrl: http://127.0.0.1:9000/
  accessKey: UFDYQGF0U315KUR2NO7K
  secretKey: nxa2+FTdjzkm36D3eUpw4YhaLRZBtC+3oaY+bxcH
  bucketName: moviefun

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG